### ISSUE TITLE
Add ability to register new sources other than just fields from models

### ISSUE THREAD

**Issue by luisiacc** [lorinkoz/django-js-choices#4]
I'd like the ability to add new sources of "choices" that are not from django models fields directly, but instead like some `value,label` pairs used for some custom logic that are not on any models and wants to be synced to a javascript frontend; I think django_js_choices would be a good place to put such logic.

I would imagine it to be something like this:

```python3
from django_js_choices import register_source

# some variable with value,label keys
DOABLE_ACTIONS = [("nothing", "Do nothing"), ("go_2", "Advance 2 steps"), ...]

register_source("doable_actions", DOABLE_ACTIONS)
```

What do you think? I'd be down for filling a PR for it.

**Comment by lorinkoz** [comment]
Awesome idea. Go4it!

Few things to keep in mind:

- How to resolve name clashes between custom choices and model choices?
- How to validate custom registered choices? (in principle, they should accept the same values that model choices accept)

**Comment by luisiacc** [comment]
> How to resolve name clashes between custom choices and model choices?

What I'd expect is for custom made names to be king of the jungle, so if there is any clashes with a field from a model, the custom one will be the one standing.

> How to validate custom registered choices? (in principle, they should accept the same values that model choices accept)

It would be as explained on [django docs for choices](https://docs.djangoproject.com/en/4.0/ref/models/fields/#choices)

> A [sequence](https://docs.python.org/3/glossary.html#term-sequence) consisting itself of iterables of exactly two items (e.g. [(A, B), (A, B) ...])

If the format is incorrect we'd warn the user and skip that source until is fixed, or maybe we just do nothing, that sounds good too, if someone has the incorrect format he'll probably will note it when using it.

Wdyt?
